### ISSUE TITLE
Export-To-Earth Plugin for Gephi 0.9.1 Fails to Install

### ISSUE THREAD

**Issue by sindimo** [gephi/gephi-plugins#105]
The ExportToEarth plugin fails to install through the plugin manager in Gephi 0.9.1, would appreciate any help to get this plugin installed. In the plugin description it refers to this link which seems to be broken:

https://github.com/gephi/gephi-plugins/exporttoearth

Thanks for the help!

**Comment by eduramiba** [comment]
Uhm, that's strange, I can confirm an error happens when installing the plugin.
WIll need to investigate this, maybe just regenerate the plugin.

**Comment by eduramiba** [comment]
This has been fixed with commit https://github.com/gephi/gephi-plugins/commit/7422759f9431805711b5e9cce315745f79658405

**Comment by sindimo** [comment]
Great it's working now, thanks a lot Eduardo for your help and quick response, I really appreciate it!

Sincerely,

Mohamad Sindi
Massachusetts Institute of Technology
MIT Center for Computational Engineering (CCE)
