### ISSUE TITLE
Neo4j Gephi 0.9 version support

### ISSUE THREAD

**Issue by hvandenb** [gephi/gephi-plugins#107]
I tried to install the plug-ins with 0.9.1 on my mac without success. It's keep needing older APIs. It seems that with 0.9 Gephi changed the way plugins are done. Is there a plan to upgrade the Neo4j plugins?

**Comment by joernroeder** [comment]
any updates on this? i'd like ti use the neo4j plugin as well with the latest 0.9 version.

**Comment by N2ITN** [comment]
I was able to install the two dependencies from here: https://github.com/mbastian/nbms-repository

After that Neo4j plugins could instal

However - when I click File --> Install Neo4j Database, these are 2 options and the response I get:
Full import --- > Select DB ---> Error window, no message
Traversal import  ---> Select DB ---> Nothing happens

See: https://github.com/gephi/gephi-plugins/issues/53

**Comment by eduramiba** [comment]
Hi Zachary,
Sorry, even if you install that, the Neo4j plugin for Gephi 0.8.2 cannot work in 0.9+

The plugin needs a complete rewrite, it's planned, but our resources are very limited.

**Comment by N2ITN** [comment]
Thanks! I'll go with 0.8.2 for now.

**Comment by cbartens** [comment]
would be awesome if this could be updated to work with 0.9* ! just tried to downloading and installing the older 0.8.2 version and doesn't even open anymore on my mac :(

**Comment by eduramiba** [comment]
There is no plan to adapt the Neo4j plugin, but you can easily connect Neo4j data to Gephi with APOC via GraphML export or even streaming plugin: https://neo4j-contrib.github.io/neo4j-apoc-procedures/

**Comment by cbartens** [comment]
Yeah we might have to do the GraphML export / import. The streaming plugin
only works reliably with very little data so effectively makes it unusable.

**Comment by mbastian** [comment]
Closing as we have a duplicate issue to cover this request, see #263.
