### ISSUE TITLE
Running geolayout makes map of countries and network disappear

### ISSUE THREAD

**Issue by WouterSpekkink** [gephi/gephi-plugins#122]
I am reporting this for someone else, whom reported this on the Gephi Facebook page. His original comment was as follows:

> everything works good with my network (I am just using nodes for now), coloring based on attribute, Map of Countries plugin all good. But as soon as I run the Geolayout based on Latitude and Longitude the map itself and all my nodes that have been displayed previously disappear. It worked previously with a similar file (only difference it was 4,000 nodes compared to 40,000 now). Has anybody similar issues. It looks fine in the Data lab also after the nodes are gone in the overview and preview.

I asked him whether he has any error reports, and he posted these:

![error1](https://cloud.githubusercontent.com/assets/6826078/15804925/1d3d99c0-2b1a-11e6-8eef-2c02d820d7ee.jpg)

![error2](https://cloud.githubusercontent.com/assets/6826078/15804932/32b9b270-2b1a-11e6-92fe-634f00899ba4.jpg)

I couldn't make anything of this, so I figured I would post it as an issue here. I'm not sure whether this is a plugin issue, or a Gephi issue. The error report seems to refer to the previewcontroller.

**Comment by mbastian** [comment]
Thanks for the report. Looks a Gephi exception indeed. I'll close the issue as a number of Preview issues were fixed in latest releases and I haven't seen this one on Sentry so far so hopefully it's fixed.
