### ISSUE TITLE
VizualizationController.selectNodes/selectEdges

### ISSUE THREAD

**Issue by jbliesener** [gephi/gephi-plugins#124]
Dear Gephi team,

I developed a plugin for Gephi 0.8.1 that was using SelectionManager.selectNodes() and .selectEdges() in order to highlight nodes and be able to manipulate them. I was also thinking about writing a new plugin that would allow to select all nodes and/or edges that have a common attribute value, as this feature doesn't exist anymore in the Filter API, which would use SelectionManager.selectNodes() and .selectEdges() as well.

From what I see, this feature does no longer exist in Gephi 0.9.1, as the corresponding functions in SelectionManager have the responsible lines commented out. See here: 
https://github.com/gephi/gephi/blob/42c003ea958a3a6dcfc232c8addb612de32193cd/modules/VisualizationImpl/src/main/java/org/gephi/visualization/api/selection/SelectionManager.java#L174

I'd like to ask if there's any specific reason for this and if there are any plans to bring back this feature, which, indeed, is important for my work.

Is there anything that I can contribute to make it work again?

**Comment by eduramiba** [comment]
Hi, I think these are supposed to come back, but @mbastian knows better about visualization api.

**Comment by jbliesener** [comment]
Thank you, Eduardo.

**Comment by jbliesener** [comment]
@mbastian Mathieu, can you just give me a position on this, please? Was it removed due to performance reasons? Any chance to get it back soon? 

From what I understand, this issue also is the reason why the Filter UI doesn't provide a "Select" button anymore, right?

Currently, this requires me to backport my latest changes to 0.8.2. And 0.8.2 has all the support issues with Java 8, MacOS etc.

**Comment by jbliesener** [comment]
Reiterating ping.... @eduraimba @mbastian 

Any news on this?

**Comment by eduramiba** [comment]
Sorry, no progress on this yet.

**Comment by jbliesener** [comment]
Thank you, @eduramiba . Requires me to continue working with 0.8.2 and Java 1.7. Sigh...

**Comment by eduramiba** [comment]
I created a related issue at https://github.com/gephi/gephi/issues/1562

**Comment by eduramiba** [comment]
Hi, this should be fixed in 0.9.2-SNAPSHOT with commit https://github.com/gephi/gephi/commit/577e2ca8f1e53ccf2a2e6e470256855699bab4b3

**Comment by jbliesener** [comment]
Thank you, Eduardo. Will this also [bring back the "Select" button on the filter panel](https://github.com/gephi/gephi/blob/master/modules/DesktopFilters/src/main/java/org/gephi/desktop/filters/FiltersPanel.java#L84)?

**Comment by jbliesener** [comment]
Well, obviously it didn't, as the button is still hidden in source code. The question was what's left missing now to reenable it... Can I help?

**Comment by eduramiba** [comment]
Oh I forgot to do that, let me check it.

**Comment by eduramiba** [comment]
It works but rigth clicking does not work, as if no nodes were selected. I will need to investigate this.
I close this and reopen https://github.com/gephi/gephi/issues/1562
