### ISSUE TITLE
Dependency artifacts repository

### ISSUE THREAD

**Issue by gabrielgonzaga** [gephi/gephi-plugins#128]
Hello,

I am using Netbeans 8.1, Maven 3.3.9 and Gephi 0.9.1.
Issue #77 is somehow similar to what I am having now, but in my case, it builds. The solution proposed was to add a module but, in my case, I already have a module and followed exactly what was proposed but nothing seems to solve my issue. On the gephi-plugins the following error appears:

Your project has dependencies that are not resolved locally. Code completion in the IDE will not include classes from these dependencies or their transitive dependencies (unless they are among the open projects).
Please download the dependencies, or install them manually, if not available remotely.

The artifacts are:
 org.netbeans.modules:org-netbeans-core-startup-base:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-core-startup:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-libs-asm:nbm-file:RELEASE81
org.netbeans.api:org-openide-filesystems-compat8:nbm-file:RELEASE81
org.netbeans.api:org-openide-filesystems:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-bootstrap:nbm-file:RELEASE81
org.netbeans.api:org-openide-modules:nbm-file:RELEASE81
org.netbeans.api:org-openide-util-lookup:nbm-file:RELEASE81
org.netbeans.api:org-openide-util-ui:nbm-file:RELEASE81
org.netbeans.api:org-openide-util:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-api-annotations-common:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-api-intent:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-api-io:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-api-progress-compat8:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-api-progress-nb:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-api-progress:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-api-templates:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-core-io-ui:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-core-multitabs:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-core-windows:jar:RELEASE81
org.netbeans.api:org-netbeans-core-multiview:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-core-nativeaccess:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-libs-jna:jar:RELEASE81
org.netbeans.modules:org-netbeans-libs-jna-platform:jar:RELEASE81
org.netbeans.modules:org-netbeans-core-network:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-core-ui:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-core-windows:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-core:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-lib-uihandler:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-libs-javafx:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-libs-jna-platform:nbm-file:RELEASE81
net.java.dev.jna:jna-platform:jar:4.1.0
org.netbeans.modules:org-netbeans-libs-jna:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-applemenu:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-autoupdate-cli:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-modules-autoupdate-services:jar:RELEASE81
org.netbeans.api:org-netbeans-modules-autoupdate-services:nbm-file:RELEASE81
org.netbeans.external:updater:jar:RELEASE81
org.netbeans.api:org-netbeans-modules-autoupdate-ui:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-modules-editor-mimelookup:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-keyring-fallback:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-keyring-impl:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-keyring-fallback:jar:RELEASE81
org.netbeans.api:org-netbeans-modules-keyring:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-masterfs-linux:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-masterfs:jar:RELEASE81
org.netbeans.modules:org-netbeans-modules-masterfs-macosx:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-masterfs-nio2:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-modules-masterfs-ui:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-masterfs-windows:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-masterfs:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-modules-options-api:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-options-keymap:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-progress-ui:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-modules-queries:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-modules-sendopts:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-modules-settings:nbm-file:RELEASE81
org.netbeans.modules:org-netbeans-modules-templates:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-modules-uihandler:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-lib-uihandler:jar:RELEASE81
org.netbeans.api:org-netbeans-spi-quicksearch:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-swing-outline:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-swing-plaf:nbm-file:RELEASE81
org.netbeans.api:org-netbeans-swing-tabcontrol:nbm-file:RELEASE81
org.netbeans.api:org-openide-actions:nbm-file:RELEASE81
org.netbeans.api:org-openide-awt:nbm-file:RELEASE81
org.netbeans.api:org-openide-dialogs:nbm-file:RELEASE81
org.netbeans.api:org-openide-execution-compat8:nbm-file:RELEASE81
org.netbeans.api:org-openide-execution:jar:RELEASE81
org.netbeans.api:org-openide-filesystems-compat8:jar:RELEASE81
org.netbeans.api:org-openide-execution:nbm-file:RELEASE81
org.netbeans.api:org-openide-explorer:nbm-file:RELEASE81
org.netbeans.api:org-openide-filesystems-nb:nbm-file:RELEASE81
org.netbeans.api:org-openide-io:nbm-file:RELEASE81
org.netbeans.api:org-openide-loaders:nbm-file:RELEASE81
org.netbeans.api:org-openide-nodes:nbm-file:RELEASE81
org.netbeans.api:org-openide-text:nbm-file:RELEASE81
org.netbeans.api:org-openide-windows:nbm-file:RELEASE81

No idea why this specif dependencies are not found for download. Everything else seems fine.
What might be wrong?

**Comment by eduramiba** [comment]
Hi, this message usually appears if your code imports classes from a transitive dependency.
You need to add a direct dependency to the artifact in your pom to fix it.

**Comment by joancf** [comment]
I got the same problem with netbeans 8.2 ... I could solve it by adding some extra information to the mojo plugin in the pom..
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>nbm-maven-plugin</artifactId>
                    <version>3.14</version>
                     <extensions>true</extensions> 
                      <inherited>true</inherited>	
                </plugin>
