### ISSUE TITLE
g.getEdgeAttributes returns node attributes

### ISSUE THREAD

**Issue by murk151** [gephi/gephi-plugins#135]
In python scripting module

gephi-plugins/modules/ScriptingPlugin/src/main/java/org/gephi/scripting/wrappers/GyGraph.java:207
`Column column = graphModel.getNodeTable().getColumn(i);`

should be:
`Column column = graphModel.getEdgeTable().getColumn(i);`

**Comment by eduramiba** [comment]
Fixed, thanks for the report.

**Comment by eduramiba** [comment]
Will release soon

**Comment by eduramiba** [comment]
The fix is now available through the update center.
