### ISSUE TITLE
Class name conflict between ExcelCsvImporter plugin and SimilarityComputer

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi-plugins#153]
To reproduce:

- Install both plugins ExcelCsvImporter and SimilarityComputer.
- Run the SimilarityComputer

Result:

java.lang.ClassCastException: net.clementlevallois.excelcsvimporter.wizard.Panel1 cannot be cast to net.clementlevallois.wizard.Panel1
	at net.clementlevallois.controller.MyFileImporter.execute(MyFileImporter.java:77)

It seems that the plugin SimilarityComputer, when casting to Panel1, retrieves a class from outside it, located in net.clementlevallois.excelcsvimporter.wizard.Panel1

The solution surely consists in making packages from each plugins private, so that they don't interfere with each other? Not sure how to do this. Waiting for instructions :-)

**Comment by eduramiba** [comment]
See #154
