### ISSUE TITLE
Neo4j REST or BOLT support

### ISSUE THREAD

**Issue by naisanza** [gephi/gephi-plugins#160]
Gephi has potential in being a GUI used for modifying and editing a Neo4j database directly via HTTP or Bolt

It would be great to have this functionality

**Comment by eduramiba** [comment]
Hi, this was possible in Gephi 0.8.2 (https://github.com/gephi/gephi/releases/tag/v0.8.2) but it's not easy to migrate to 0.9.1, though it's in the wishlist.

**Comment by eduramiba** [comment]
See #107

**Comment by cbartens** [comment]
would be awesome if this could be updated to work with 0.9* ! just tried to downloading and installing the older 0.8.2 version and doesn't even open anymore on my mac :(

**Comment by mbastian** [comment]
Closing as we have a new issue to cover this request #263
