### ISSUE TITLE
error map of countries

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi-plugins#166]
I recently noticed a bug. The problem occurs when I load a gexf file that already has a set of variables called lat/lng that are doubles. After I load the file and then go to Map of Countries the plugin creates *another* two variables called lat/lng.

I would like to plot both my data and the map data at the same time. However, right now if I select one set of lat/lng variables only the map OR my data will be properly located (NOT both). When I check the "Data Laboratory" there are actually two sets of lat/lng variables set!

I can work around this by creating a new variable and merging both variables into it. This is a pain though.

**Comment by eduramiba** [comment]
Does the gexf file use 'lat' and 'lang' as the column ids or titles only? A column created from data lab will have 'lat' both for id and title, and it's the id the one that does the actual matching.

**Comment by mbastian** [comment]
Hey @seinecle, I looked at the map of countries plugin code and the column matching/creation seems correct to me. I'm therefore not able to reproduce this issue. Let me know if this issue persists otherwise I'll close.

**Comment by mbastian** [comment]
@seinecle let me know if that's still an issue. Otherwise we can close.
