### ISSUE TITLE
[MultimodeNetworksTransformationPlugin] All edges get lost when transforming 2-mode to 1-mode

### ISSUE THREAD

**Issue by michihenninger** [gephi/gephi-plugins#168]
The new version of the MultimodeNetworksTransformationPlugin 1.0.1 (released at Aug 10) seemes to have introduced a bug. We are not able to transform a 2-mode network into a one-mode network. After the transformation all edges are disapprared. (But removing edges was not selected)

I have a workaround (install older version manually) but I would appreciate using the plugin manager and having a working version.

**Comment by joancf** [comment]
Yes I found that error, it happens in some networks, not always.
 I did some changes to that plugin some time ago, but I can't get the code of the current version of the plugin for gephi 9.2

**Comment by eduramiba** [comment]
Related: https://github.com/gephi/gephi/issues/1854

**Comment by mbastian** [comment]
Looks like this was merged already. Thanks!
