### ISSUE TITLE
Twitter Importer

### ISSUE THREAD

**Issue by jcmundy** [gephi/gephi-plugins#175]
I really like the twitter streaming importer plugin, but I am not sure if I am using it entirely correctly.  When I load a #hashtag network, it does not always show the actual hashtags that I searched, only the ones to which they are connected.  Because I am searching on more than one hashtag that leaves me unsure of the actual hashtag network overlap.  Am I inputting something incorrectly?  Is there a way to set it so that if I search #gephi and #networkanalysis I could see to which of those the appearing hashtags are connected?  Thank you!

**Comment by eduramiba** [comment]
@totetmatt may know better

**Comment by totetmatt** [comment]
Hiho, 
Yes it's intended to remove the hashtags that are on the query list. The reason behind is to avoid a 'star' / 'hairball' effect centered on the hashtag in the query (as all of the result will for sure contain it)

But a bug / feature to avoid that is to query your hashtag with the hashtag (#) so for example if you query like this:
```
#hashtagA 
hashtagB
```

Then the hashtagA will be kept as a node, whereas hashtagB won't be displayed

**Comment by jcmundy** [comment]
Thank you!  That works for me.
