### ISSUE TITLE
NBM Maven Plugin configuration issues in IntelliJ IDEA

### ISSUE THREAD

**Issue by cbartosiak** [gephi/gephi-plugins#179]
Hi,

IntelliJ IDEA marks `authorUrl` and `sourceCodeUrl` red and show the message _Element ... is not allowed here_. Is it expected?

Note the maven build works.

**Comment by eduramiba** [comment]
Mmm not sure about that, just ignore it for the moment,

**Comment by cbartosiak** [comment]
OK, as long as the build works it's only irritating a little bit ;)

**Comment by mbastian** [comment]
Yes I agree it's not ideal. I've added a ticket on the Maven plugin to sort this out.
