### ISSUE TITLE
Custom FA2 plugin help

### ISSUE THREAD

**Issue by juliannej** [gephi/gephi-plugins#194]
Hi,

I want to build a custom version of the ForceAtlas2 layout plugin that will add node weight influence. I have looked at the code, but it isn't entirely clear to me where the layout edge weight calculations are (ie in which folder in the FA2 plugin). Could you let me know where I would find this in the folder?

Thanks,
Julianne

**Comment by eduramiba** [comment]
Hi,
It seems to be here https://github.com/gephi/gephi/blob/master/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/forceAtlas2/ForceAtlas2.java#L207
