### ISSUE TITLE
Create default empty column

### ISSUE THREAD

**Issue by juliannej** [gephi/gephi-plugins#196]
I am working on a plugin for node weight. I want 'weight' to become a default column once my plugin (layout) is selected that can be overwritten if the data already had a column entitled 'weight' or if the user wants to copy over a column they already have to act as node weight. 

Do you think it is possible to do this for my plugin? Is this the correct place to ask? Would I be using the ToolKit (e.g. addColumn())?

The example I am following is the multi gravity plugin, but they don't create a column by default - they just read the column if present or use 0 and inform the user that they are missing attribute(s).

**Comment by eduramiba** [comment]
Sure, you can add the column if missing, but also make sure to validate that the column with that id might already exist and have a different type (non numeric), in which case you have to tell the user it's incorrect.

**Comment by juliannej** [comment]
The actual addition - would this be using the toolkit addColumn() function?

**Comment by juliannej** [comment]
I think this would be the case. If I want to allow weight to be a dynamic property OR a static property - what do I put in **type** when I am adding the column?
e.g.
addColumn(String id, Class **type**)

**Comment by juliannej** [comment]
Thank you. With addColumn() do I expect that a new column should be visible in Data Observatory? So far I have not been able to do this. Do I need to alter the table after import?

**Comment by eduramiba** [comment]
It should not be necessary, data laboratory does it like this: https://github.com/gephi/gephi/blob/master/modules/DataLaboratoryAPI/src/main/java/org/gephi/datalab/impl/AttributeColumnsControllerImpl.java#L124

**Comment by juliannej** [comment]
Sorry - can you clarify:
1. whether I would be able to call this on an instance of Table?
2. what package I need to import to access this?

Thank you,
Julianne

**Comment by eduramiba** [comment]
Yes, you should only need to call addColumn on the nodes table.
Does it succeed? Then you should be able to see the column in the data laboratory table, it should be that simple.

Other example: https://github.com/gephi/gephi/blob/master/modules/StatisticsPlugin/src/main/java/org/gephi/statistics/plugin/Modularity.java#L641

**Comment by juliannej** [comment]
Thank you!!
