### ISSUE TITLE
failed to execute goal (default-manifest) - module has friend dependency

### ISSUE THREAD

**Issue by UTH-Tuan** [gephi/gephi-plugins#202]
I have been receiving the following issue: Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:3.14:manifest (default-manifest) on project ... Module has friend dependency on org.netbeans.modules.masterfs but is not listed as a friend.

I am using the latest Netbeans IDE (v10) to develop a Gephi plugin for v0.9.2.

Any suggestions on fixes?

**Comment by eduramiba** [comment]
Can you show your code? Netbeans modules dependencies are a bit tricky sometimes.

**Comment by MFAmithUTH** [comment]
Thanks for the response, I actually manged to fix it by adding this to the dependency: <scope>provided</scope>

However I am encountering a similar issue with another dependency 
"org.netbeans.core.startup but is not listed as a friend"

I am using the Netbeans GUI Builder to layout the panel for my statistics module

**Comment by mbastian** [comment]
Hi @UTH-Tuan, were you able to fix your issue?

**Comment by UTH-Tuan** [comment]
Yes
