### ISSUE TITLE
Can't resolve dependencies

### ISSUE THREAD

**Issue by harrismirza** [gephi/gephi-plugins#214]
Hi, I am using IntelliJ 2019.2.3, Gephi 0.9.2 and Maven 3.6.1.

For some reason, it can't seem to find the dependencies when I add the project to my IDE. I haven't written any code yet.

The full error that is shown when running maven clean install -x is:
[ERROR] Failed to execute goal on project gephi-plugins: Could not resolve dependencies for project org.gephi:gephi-plugins:pom:0.9.2: The following artifacts could not be resolved: org.netbeans.modules:org-netbeans-core-startup-base:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-startup:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-libs-asm:nbm-file:RELEASE82, org.netbeans.api:org-openide-filesystems-compat8:nbm-file:RELEASE82, org.netbeans.api:org-openide-filesystems:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-bootstrap:nbm-file:RELEASE82, org.netbeans.api:org-openide-modules:nbm-file:RELEASE82, org.netbeans.api:org-openide-util-lookup:nbm-file:RELEASE82, org.netbeans.api:org-openide-util-ui:nbm-file:RELEASE82, org.netbeans.api:org-openide-util:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-annotations-common:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-intent:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-io:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-progress-compat8:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-progress-nb:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-progress:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-templates:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-io-ui:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-core-multitabs:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-core-multiview:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-nativeaccess:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-network:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-ui:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-windows:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-lib-uihandler:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-libs-javafx:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-libs-jna-platform:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-libs-jna:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-applemenu:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-autoupdate-cli:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-autoupdate-services:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-autoupdate-ui:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-keyring-fallback:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-keyring-impl:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-keyring:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs-linux:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs-macosx:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs-nio2:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-masterfs-ui:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs-windows:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-options-api:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-options-keymap:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-progress-ui:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-queries:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-sendopts:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-settings:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-templates:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-uihandler:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-swing-outline:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-swing-plaf:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-swing-tabcontrol:nbm-file:RELEASE82, org.netbeans.api:org-openide-actions:nbm-file:RELEASE82, org.netbeans.api:org-openide-awt:nbm-file:RELEASE82, org.netbeans.api:org-openide-dialogs:nbm-file:RELEASE82, org.netbeans.api:org-openide-execution-compat8:nbm-file:RELEASE82, org.netbeans.api:org-openide-execution:nbm-file:RELEASE82, org.netbeans.api:org-openide-explorer:nbm-file:RELEASE82, org.netbeans.api:org-openide-filesystems-nb:nbm-file:RELEASE82, org.netbeans.api:org-openide-io:nbm-file:RELEASE82, org.netbeans.api:org-openide-loaders:nbm-file:RELEASE82, org.netbeans.api:org-openide-nodes:nbm-file:RELEASE82, org.netbeans.api:org-openide-text:nbm-file:RELEASE82, org.netbeans.api:org-openide-windows:nbm-file:RELEASE82: Could not find artifact org.netbeans.modules:org-netbeans-core-startup-base:nbm-file:RELEASE82 in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project gephi-plugins: Could not resolve dependencies for project org.gephi:gephi-plugins:pom:0.9.2: The following artifacts could not be resolved: org.netbeans.modules:org-netbeans-core-startup-base:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-startup:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-libs-asm:nbm-file:RELEASE82, org.netbeans.api:org-openide-filesystems-compat8:nbm-file:RELEASE82, org.netbeans.api:org-openide-filesystems:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-bootstrap:nbm-file:RELEASE82, org.netbeans.api:org-openide-modules:nbm-file:RELEASE82, org.netbeans.api:org-openide-util-lookup:nbm-file:RELEASE82, org.netbeans.api:org-openide-util-ui:nbm-file:RELEASE82, org.netbeans.api:org-openide-util:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-annotations-common:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-intent:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-io:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-progress-compat8:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-progress-nb:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-progress:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-api-templates:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-io-ui:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-core-multitabs:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-core-multiview:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-nativeaccess:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-network:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-ui:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core-windows:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-core:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-lib-uihandler:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-libs-javafx:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-libs-jna-platform:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-libs-jna:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-applemenu:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-autoupdate-cli:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-autoupdate-services:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-autoupdate-ui:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-keyring-fallback:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-keyring-impl:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-keyring:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs-linux:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs-macosx:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs-nio2:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-masterfs-ui:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs-windows:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-masterfs:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-options-api:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-options-keymap:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-progress-ui:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-queries:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-sendopts:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-settings:nbm-file:RELEASE82, org.netbeans.modules:org-netbeans-modules-templates:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-modules-uihandler:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-swing-outline:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-swing-plaf:nbm-file:RELEASE82, org.netbeans.api:org-netbeans-swing-tabcontrol:nbm-file:RELEASE82, org.netbeans.api:org-openide-actions:nbm-file:RELEASE82, org.netbeans.api:org-openide-awt:nbm-file:RELEASE82, org.netbeans.api:org-openide-dialogs:nbm-file:RELEASE82, org.netbeans.api:org-openide-execution-compat8:nbm-file:RELEASE82, org.netbeans.api:org-openide-execution:nbm-file:RELEASE82, org.netbeans.api:org-openide-explorer:nbm-file:RELEASE82, org.netbeans.api:org-openide-filesystems-nb:nbm-file:RELEASE82, org.netbeans.api:org-openide-io:nbm-file:RELEASE82, org.netbeans.api:org-openide-loaders:nbm-file:RELEASE82, org.netbeans.api:org-openide-nodes:nbm-file:RELEASE82, org.netbeans.api:org-openide-text:nbm-file:RELEASE82, org.netbeans.api:org-openide-windows:nbm-file:RELEASE82: Could not find artifact org.netbeans.modules:org-netbeans-core-startup-base:nbm-file:RELEASE82 in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)

**Comment by eduramiba** [comment]
You will need to add the netbeans repositories as in our pom.xml: https://github.com/gephi/gephi/blob/master/pom.xml#L257

In future releases it won't be necessary since new versions of Netbeans RCP artifacts are now deployed to maven central: https://mvnrepository.com/artifact/org.netbeans.api/org-openide-util

**Comment by eduramiba** [comment]
But the template for the plugin should already work as is, it includes the repository. Did you change anything in any pom?

**Comment by harrismirza** [comment]
I solved it, it was actually a duplicate of https://github.com/gephi/gephi-plugins/issues/77
