### ISSUE TITLE
HTTP Graph Plugin fail to build due to external dependency

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi-plugins#258]
The [HTTP Graph](https://gephi.org/plugins/#/plugin/httpgraph) plugin could not be migrated automatically to the 0.9.3 version of Gephi.

The error has to do with some external dependency during build. Maybe something has changed since the plugin was created.

Here is the log
```
Could not resolve dependencies for project net.phreakocious:httpgraph:nbm:1.0.8:
Failed to collect dependencies at org.membrane-soa:service-proxy-core:jar:4.3.0 -> 
javax.annotation:com.springsource.javax.annotation:jar:1.0.0: Failed to read artifact descriptor for
javax.annotation:com.springsource.javax.annotation:jar:1.0.0: Could not transfer artifact
javax.annotation:com.springsource.javax.annotation:pom:1.0.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror
for repositories: [com.springsource.repository.bundles.external (http://repository.springsource.com/maven/bundles/external,
default, releases+snapshots), predic8-releases (http://repository.membrane-soa.org/content/groups/public, default,
releases+snapshots)] -> [Help 1]
```

**Comment by mbastian** [comment]
@phreakocious Is that something you could look into? I created a branch `http-graph-plugin` updated already to the 0.9.3 base to make things easier. I also added you to the Plugin Developers team so you should have write access to this branch.

**Comment by phreakocious** [comment]
> @phreakocious Is that something you could look into? I created a branch `http-graph-plugin` updated already to the 0.9.3 base to make things easier. I also added you to the Plugin Developers team so you should have write access to this branch.

Sure, I'll have a look.

**Comment by mbastian** [comment]
@phreakocious That's a bit strange I'm not sure why you might need these two dependencies in your plugin.

Would you mind committing the current state to the `gephi/http-graph-plugin` branch so I can have a look? Thx

**Comment by phreakocious** [comment]
@mbastian - I don't believe they are required either.  Could it be due to how it's still misusing the Generator?  I pushed up a minimal set of changes that I think should at least build.

**Comment by phreakocious** [comment]
@mbastian - I dug into this a bit further.  It ultimately seems to be coming from having `io-importer-plugin` defined as a dependency.  I can remove that one and add an exclusion for `db-drivers` and get the project to build.  The one thing from that which I'm currently tied to is the `AppendProcessor`, so I'm guessing I can't rewrite around needing that which leaves me stuck.  Thoughts?

**Comment by phreakocious** [comment]
The version I have just committed is working.  Setting `verifyRuntime` to false for `nbm-maven-plugin` resolved the transitive dependency errors.

**Comment by phreakocious** [comment]
@mbastian - I've made a bunch of updates and improvements.  Downloaded Gephi 0.9.3, installed the .nbm and loaded up 108k nodes and 996k edges in a few minutes without error.  Still not sure that setting that `verifyRuntime` is the appropriate fix, though.  I'll need your input on that prior to submitting the PR..

<img width="1523" alt="Screen Shot 2022-09-01 at 10 24 10 AM" src="https://user-images.githubusercontent.com/567063/187952886-ae074198-59f0-42c3-a129-1525f02dcede.png">

**Comment by mbastian** [comment]
Awesome, At the moment I don't see an alternative to set `verifyRuntime` to `warn` or `false` as you import quite a bit of dependencies and at least one or two are clashing with non-public dependencies set elsewhere. We can clean that up at a later state so I would indeed recommend to create a PR!
