### ISSUE TITLE
mvn package clean

### ISSUE THREAD

**Issue by WouterSpekkink** [gephi/gephi-plugins#261]
I am working on a revised version of a plugin I authored earlier. After finishing the plugin, I try to run `mvn package clean`. The output is as follows (I only copy in the last lines):

```
[ERROR] Failed to execute goal org.apache.netbeans.utilities:nbm-maven-plugin:4.5:cluster (default) on project gephi-plugins: The NetBeans binary directory structure for wouterspekkink:orderedlayout:nbm:1.0.0 is not created yet.
[ERROR]  Please execute 'mvn install nbm:cluster' to build all relevant projects in the reactor.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :gephi-plugins
```
I can run the suggested `mvn install nbm:cluster` all I want (and it runs successfully), but I still end up with the same error.

Funnily enough though, the build succeeds when just using `mvn package`.

* Operating System: ArcoLinux

**Comment by mbastian** [comment]
Hi @WouterSpekkink, as part of the [changes](https://github.com/gephi/gephi-plugins/discussions/245) we made ahead of the 0.9.3 release we removed the `modules/pom.xml` file. If you're transitioning from a previous version, try to delete this file as it might interfere. That's my hypothesis, but I might be wrong. Let me know,

**Comment by WouterSpekkink** [comment]
I just checked, but I don't have the `modules/pom.xml` file. The problem persists; it only happens when I add `clean` to the command. `mvn package` works just fine.

**Comment by WouterSpekkink** [comment]
Oh dear, I am afraid I was just being an idiot. I switched `clean` and `package` in the command for some reason. `mvn clean package` works just fine. -_-
