### ISSUE TITLE
Update and test Neo4j plugin

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi-plugins#263]
We used to have a [Neo4j plugin](https://gephi.org/plugins/#/plugin/neo4j-graph-database-support) but it's out-dated and no longer works with recent versions of Neo4j.

The old plugin had fairly advanced features like lazy loading and export back to Neo4j. I would recommend to rather start simple and limit the scope to import only, based on Cypher query. 

### Definition of done
- Supports Bolt and Http protocols
- Can detect the DB version and use the appropriate driver (3 and 4?)
- Graph is imported using the ImportAPI (so that one gets validation etc.)
- Unit tests to avoid regressions in the future
- Plugin is released with documentation

### Resources
- https://neo4j.com/docs/http-api/current/actions/begin-a-transaction/
- https://neo4j.com/docs/bolt/current/bolt/
- https://github.com/gephi/gephi/wiki/Spigot-importer-with-Wizard

**Comment by sim51** [comment]
Remaining tasks : 

- [ ] Test on big dataset 
- [ ] Cancel an import 
- [ ] _Better UI layout ? (optional)_

**Comment by mbastian** [comment]
@sim51 Not sure if adding progress for each node is a good idea. It would add some overhead I think.

**Comment by sim51** [comment]
yeah, and it's fast enough to not be facing to the issue "Is my import frozen ?"

**Comment by mbastian** [comment]
Congrats, the plugin is published: https://gephi.org/plugins/#/plugin/neo4j-plugin

Fantastic work, thank you @sim51!
