### ISSUE TITLE
Export graph to JSON doesn't write Z position

### ISSUE THREAD

**Issue by kikohs** [gephi/gephi-plugins#266]
Hi,
The graphml, gexf exporter work fine but the JSON exporter doesn't write the Z coordinate in the file.

To reproduce, run a simple ForceAtlas 3D and export graph.

Thanks.

**Comment by mbastian** [comment]
JSON Export has been integrated into Gephi since version 0.10 so the plugin doesn't really make sense anymore. Report JSON export issues directly into https://github.com/gephi/gephi.
