### ISSUE TITLE
GeoLayout not working

### ISSUE THREAD

**Issue by YHLin87** [gephi/gephi-plugins#276]
## Which Plugin?
GeoLayout

## Expected Behavior
Hi, I'm using Gephi 0.9.7
I have a geolocated [node file](https://aitthai-my.sharepoint.com/:x:/g/personal/st121534_ait_ac_th/ESWUC_e0sVNLpbqNkcHOGPoBRswnMXTDTHmL2QVfAnEQ0g?e=frrhnh) and an [edge file](https://aitthai-my.sharepoint.com/:x:/g/personal/st121534_ait_ac_th/EU0hsmvB7u5HviaZQnLAXiUB9SkAHz9wN9VX3Br7MuiIwA?e=pOfnL9) and I'm trying to use the Geo Layout plug-in.
I expect to display the network based on geocoded attributes (i.e. latitude and longitude) and standard projections.

## Current Behavior
It just doesn't run at all when I click on "run", no matter how I adjust the setting.
Could anyone help to check what the problem would be. Thank you! 

## Possible Solution

Could anyone help me to figure out what the problem is?

## Steps to Reproduce

1. Import the node and edge files
2. Run GeoLayout

## Your Environment

* Gephi Version used: Gephi 0.9.7
* Plugin Version used: GeoLayout 1.0.0
* Operating System: Windows 11

**Comment by mbastian** [comment]
Hi, there are a few pitfalls you might run into:
- Make sure you lat/lon columns are imported with a "double" or "float" type. Otherwise it won't be sorted.
- When exporting from Excel make sure you use "." for decimals, "123.3" and not "123,3"

Hope this helps

**Comment by YHLin87** [comment]
Hi Bastian,

Thanks for your kind reminder. 
I just double checked: lat/long are imported with a double type, and I use "." not ",".

Actually my original files had about 130 nodes and 100+ edges. They worked.
But when I expanded the data points to 350+ nodes and 600+ edges (in the same files), they just don't work anymore. The nodes and edges would disappear as soon as I clicked on "run". Even if I tried to reapply other layouts, they wouldn't reappear... 

I reinstalled Gephi and the plugin at least 3 times, the issue remains...

**Comment by mbastian** [comment]
Strange. Seems like you can reproduce this issue every time so that's helpful. WOuld you mind sending me those graph files at mathieu.bastian [at] gephi.org. I can have a deeper look.

**Comment by YHLin87** [comment]
Thanks so much for your kind offer. I just sent across the files. Looking forward to learning how to make it work.

**Comment by mbastian** [comment]
Hi @YHLin87 I had a quick look and the problem is with your data. There is one node with an erroneous longitude (see screenshot). That makes the whole graph very wide due to this one node, causing the rest of the nodes to be hard to find. If I delete this node, it works fine.

Also, because your coordinates are so close from each other, you may need to increase the GeoLayout scale. 

<img width="1006" alt="Screenshot 2022-09-19 at 09 24 43" src="https://user-images.githubusercontent.com/234813/190968527-bdd54cac-7aae-4e6b-a467-76c697babc2a.png">

**Comment by YHLin87** [comment]
Hi Mathieu,

Thanks so much for helping to sort this out.
Now it works!

Best regards,
Yung
