### ISSUE TITLE
Twitter Streaming Importer v2 not found in Gephi-Plugins

### ISSUE THREAD

**Issue by Pigeon-Effect** [gephi/gephi-plugins#301]
Hello,

Unfortunately I cant find the Twitter Streaming Importer v2 under available Plugins in Gephi. Has it been removed? Can Anyone upload the file here so we can import it from internal memory? 

Thanks! :)

**Comment by totetmatt** [comment]
Strange it looks available with latest version of Gephi 0.10.1. 

Can you give us more context ? Version of Gephi ? OS ? Did you click on "check for newest" ? Are you in a geographical zone where an internet filter could  applied ? 

![image](https://user-images.githubusercontent.com/749891/231804701-8cf8ffdf-6791-4889-aa31-1b4bf2df3c95.png)

**Comment by Pigeon-Effect** [comment]
I just realised that having the newest Version of Gephi 0.9.2 doesnt mean having Gephi 0.10.1. I found the Plugin as supposed with the new Version. 

Thanks for the quick reply! :)
