### ISSUE TITLE
Improving Default Permissions on Windows

### ISSUE THREAD

**Issue by carlschroedl** [gephi/gephi-plugins#33]
After cloning this project to a windows machine, opening in NetBeans 7.4 and building, I cannot successfully run the project. I get Access Denied errors on .dll and .exe files in gephi-plugins/platforms/*.

**Comment by mbastian** [comment]
We've migrated to a new maven-based architecture so no longer embed the exe/dll directly in the repository. Closing as not relevant anymore.
