### ISSUE TITLE
Support Neo4J 2.0

### ISSUE THREAD

**Issue by andrewwakeling** [gephi/gephi-plugins#37]
It would be great if the plugin could be upgraded to support Neo4J 2.0.

Related [stackoverflow question](http://stackoverflow.com/questions/19733615/gephi-fails-to-import-neo4j-data).

The current error suggests setting `allow_store_upgrade=true` but this did not fix my problem and I still get the same error.

**Comment by mbastian** [comment]
Closing as we have a duplicate issue to cover this request, see #263.
