### ISSUE TITLE
Streamer, nodes for groups, "cn" on non-existing group

### ISSUE THREAD

**Issue by gaborcsardi** [gephi/gephi-plugins#38]
I noticed that grouping nodes in Gephi generates some streamer events:

```
{"cn":{"78":{}}}
{"cn":{"78":{"Label":"Group (77 nodes)"}}}
{"an":{"78":{"g":0.67603743,"b":0.652508,"r":0.5715301,"Label":"Group (77 nodes)","z":0,"y":-6.341315E-6,"x":-7.133979E-6,"size":149.01709}}}
```

It is somewhat unexpected that grouping would change the graph itself, but I can accept that grouping means contracting nodes into a single node.

But is it OK, that a "change node" event is sent on non-existing node "78" first? I guess that the node should be added first, and then changed.

**Comment by mbastian** [comment]
Thanks for the report. Closing as we no longer support hierarchical graphs anyway
