### ISSUE TITLE
Unable to access neo4j 2.01 version db

### ISSUE THREAD

**Issue by kodo651** [gephi/gephi-plugins#40]
I'm running Gephi 0.8.2-Beta together with the "Neo4j Graph Database support" plugin updated on March 3, 2014. I've used the BatchImporter to generate a neo4j-database but when I tried to open it from Gephi, I get an org.neo4j.graphdb.NotInTransactionException. The generated db opens up without any problems in neo4j and can be browsed from the web-admin.

I also tried to open the sample test database created by the 2.01 installer and get exactly the same exception.

Is this a known problem or have I missed something here?

**Comment by pramttl** [comment]
File -> Neo4j Database -> Full Import

Finder opens (on Mac OS X Yosemite)

Even though the filter in Finder is set to "All Files". I see no files even though there are files.

Confused, unable to import Neo4j database. It would be much easier if we could give connection parameters to the `Neo4j` database like localhost:7474 and then using the Neo4j REST API if Gephi could fetch the data.

**Comment by hashamMunir** [comment]
same problem trying to import neo4j datbase into gephi, popup window with warning sign and no text on it.

**Comment by birbilis** [comment]
indeed it would be better if it could read and update a database from a remote server. Might take more time but could be more useful for (turn-based) collaboration too

**Comment by mboeing3** [comment]
@birbilis: I specifically need the plugin to read from disk, because for some applications the sheer amount of data makes it necessary to avoid any bottlenecks (as a remote interface often is). Of course it would be neat if the option to access remote servers would be added, but the direct input should remain.

**Comment by birbilis** [comment]
@mboeing3: Sigma.js library (on github) has code to import/export neo4j data via Cypher. Maybe could adapt implementation from there into the same or separate plugin. 

BTW, with latest Neo4j and Gephi the import doesn't seem to work, shows that empty warning dialog

**Comment by mbastian** [comment]
Closing as we have a duplicate issue to cover this request, see #263.
