### ISSUE TITLE
Doesn't see Java 1.7 on Mavericks

### ISSUE THREAD

**Issue by yannis1962** [gephi/gephi-plugins#42]
When I saw the error message "Neo4j plugin requires Java 1.7", I installed Java 1.7 JRE on my Mavericks machine. When I ask for java -version I get

java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

But the plugin still doesn't want to get installed in Gephi, it simply doesn't see the new Java version. What can I do?

**Comment by mbastian** [comment]
Closing as we have a duplicate issue to cover this request, see #263.
