### ISSUE TITLE
[neo4j-plugin] Node labels are not imported

### ISSUE THREAD

**Issue by hbruch** [gephi/gephi-plugins#46]
Currently, node labels are not imported. As a neo4j node might have multiple labels, an import should, in analogy to neo4j_relationship_type property for relationships, have a neo4j_node_label property of type LIST_STRING (though I'm not sure how well operations on LINE_STRING properties are supported?)

**Comment by mbastian** [comment]
Closing as we have a duplicate issue to cover this request, see #263.
