### ISSUE TITLE
Neo4j database in gephi full import not working - empty warning mess

### ISSUE THREAD

**Issue by sduchh** [gephi/gephi-plugins#53]
Hi, I'm having some difficulty in importing a Neo4j database into Gephi using the Neo4j plugin: when I go to File > Neo4j Database > Full Import and try to import a database, I get a popup with an empty warning message. I have also tried a Traversal Import, but after selecting the database, no windows pop up.

**Comment by mbastian** [comment]
Closing old issue, a new Neo4J plugin was just developed and released. Check it out https://gephi.org/plugins/#/plugin/neo4j-plugin
