### ISSUE TITLE
Full import Problem for neo4j-community 2.1.7 with gephi 0.8.2

### ISSUE THREAD

**Issue by vedavidhbudimuri** [gephi/gephi-plugins#55]
Im using neo4j-community 2.1.7 with gephi 0.8.2 when im trying to full import a pop out is comming out saying warning with no message in it. And import fails. Im working on ubuntu 14.04

**Comment by eladpr** [comment]
it now works with 2.1.7, but not with the newest neo4j 2.2.0 version, gives a blank warning

**Comment by mbastian** [comment]
Closing as we have a duplicate issue to cover this request, see #263.
