### ISSUE TITLE
neo4j 2.2 support

### ISSUE THREAD

**Issue by FlxVctr** [gephi/gephi-plugins#58]
Please add neo4j 2.2(.1) support, as neo4j has major performance improvements in 2.2.

At the moment it only gives an empty warning if I try to import (and yes, database is shut down.)

Cheers :)

**Comment by ojcitt** [comment]
I too see a blank error message when trying to import my Neo4j database on Windows 7, JRE 7, Neo4j 2.2.0.

In the interim, what's the best way to get a graph out of Neo4j 2.2 and into Gephi 0.8.2? I suppose I could write my own little wrapper, or do a CSV export of some sort.

**Comment by FlxVctr** [comment]
Best way is to export graphml with shell tools: https://github.com/jexp/neo4j-shell-tools though it doesn't get the labels right and you will have to correct the graphml file to do so.

**Comment by ojcitt** [comment]
@FlxVctr Thank you. For the moment I've got it working with spreadsheet formats for the node and edge lists, since the queries to build them are straightforward and I don't need to round-trip the data back to neo4j yet. I'll have to check out the shell tools, too.

**Comment by eduramiba** [comment]
It will be more difficult than expected to adapt Neo4j to Gephi 0.9, since the new core no longer has the old delegates system.

Probably the new Neo4j plugin will be a simple importer and exporter of Neo4j files.

**Comment by FlxVctr** [comment]
That would be sad as dynamic loading would be handy to explore very large graphs ... if I get you right. What do you exactly mean by Neo4j-files?

**Comment by eduramiba** [comment]
I mean the database files. I still need to study what options we have. Also I'm not a neo4j expert at all...

**Comment by mbastian** [comment]
Closing as we have a duplicate issue to cover this request, see #263.
