### ISSUE TITLE
link in plugins dialog of "Linkflucence Plugin" is wrong

### ISSUE THREAD

**Issue by jongleur1983** [gephi/gephi-plugins#96]
the link to the homepage of the "Linkflucence Plugin" in the Available plugins page refers to http://github.com/gephi/gephi-plugins/linkfluence-plugin which is a dead link.
I'm not sure how the overall gephi project is organized as it looks like it's in some refactoring stage.

Observed with linkfluence plugin version 1.0.9 form March 19th, 2016 in Gephi 0.9.1

**Comment by eduramiba** [comment]
Right, this is the correct link now: https://github.com/eduramiba/gephi-plugins/tree/linkfluence-plugin

Thanks for the notice.
